  
version: 1
jobs:
  build:
    image: node:10
    script:
        - npm install
        - npx truffle compile

  test:
    image: node:10
    script:
        - npm install
        - npx truffle test

  deploy_ropsten_metamask:
    image: node:10
    script:
        - npm install
        - ./node_modules/.bin/truffle migrate --network ropsten_metamask --reset

stages:
  - build_and_test:
      jobs: 
        - build
        - test
  - deploy_ropsten_metamask:
      jobs:
        - deploy_ropsten_metamask:
            when: manual
