version: 1
jobs:
  deploy_to_prod:
    image: alpine
    script:
      - echo patata
    
  push_to_docker_registry_prod:
    image: alpine
    script:
      - echo patata2

stages:
  - build_prod:
      jobs:
        - push_to_docker_registry_prod:
            when: manual
            allowFailure: false
            filters:
              only:
                - other
  - deploy_prod:
      jobs:
        - deploy_to_prod:
            filters:
              only:
                - other
