version: 1
jobs:
  deploy_ropsten_metamask:
    type:
      name: ethereum/deploy
    image: node:10
    script:
        - npm install
        - npx truffle  migrate --network=ropsten_metamask --verbose-rpc --reset

stages:
  - deploy_ropsten_metamask:
      jobs:
        - deploy_ropsten_metamask
