version: 1
jobs:
  deploy_ropsten_metamask:
    image: node:10
    type:
      name: ethereum/deploy
    script:
      - npm install
      - ./node_modules/.bin/truffle migrate --network rinkeby_metamask --reset

stages:
  - deploy_ropsten_metamask:
      jobs:
        - deploy_ropsten_metamask
